name: douban
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      douban-name:
        description: 'DouBan Id'
        required: false  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    name: Douban Sync
    runs-on: ubuntu-latest
    env:
      DOUBAN_NAME: ${{ secrets.DOUBAN_NAME }}
      REF: ${{ github.ref }}
      REPOSITORY: ${{ github.repository }}
      YEAR: ${{ vars.YEAR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/douban-requirements.txt
      - name: Douban Movie sync
        run: |
          python -u scripts/douban.py  
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: DOUBAN Sync  # 提交者的GitHub用户名
          author_email: DOUBAN Sync  # 提交者的电子邮件
          message: 'Automatically commit changes'  # 提交信息
          add: '.'  # 添加当前目录下的所有变更
